"""empty message

Revision ID: 5820bed09f95
Revises: 
Create Date: 2023-10-12 11:48:51.782203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5820bed09f95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakeries_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cakes_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cake_bakeries_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('bake_id', sa.Integer(), nullable=False),
    sa.Column('cake_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bake_id'], ['bakeries_table.id'], name=op.f('fk_cake_bakeries_table_bake_id_bakeries_table')),
    sa.ForeignKeyConstraint(['cake_id'], ['cakes_table.id'], name=op.f('fk_cake_bakeries_table_cake_id_cakes_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cake_bakeries_table')
    op.drop_table('cakes_table')
    op.drop_table('bakeries_table')
    # ### end Alembic commands ###
